# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://us1s.github.io/ssss'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /ssss

# Title of the Site
title: us1s
# Description of the Site
description: Brain Storage in us1s
# URL of Image of the Site
site-image: /assets/images/metaa.jpg
# Keywords of the Site
site-keywords: web, hack, IT, HW
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/metaa.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: aced@kakao.com
#facebook_username: hojjijji
#twitter_username: thedevslot
#instagram_username: thedevslot
#linkedin_username: thedevslot
github_username:  us1s
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
dribbble_username: /
spotify_username: hojjijji

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: us1s
# URL for the Image of the Author
author-image: /assets/images/userimg.jpg
# 60 Words About the Author
author-about: Kim_Soohyun<br>_21.10 - ISO/IEC27001_내부심사원<br>_21.06 - 정보보안_산업기사
#HIGH :<br>MID : web_hacking, C, Python, Linux<br>LOW : powershell_script, shell_script, batch_script, bootstrap, mysql, mongodb, ASA, paloalto, sniper_IPS, reversing, php, html/css, ML(jupyter/Pandas/Scikit_learn), docker


# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://t.me/hojjijji

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
